pagetitle: Resume
title: Chris J. Nicolini
subtitle: Social Media | Content Producer | Journalist | Newsie
---

<style type="text/css">
h1.title, h2.subtitle, h3.subtitle {
  text-align: center;
}
</style>

<center> <i class="fa fa-envelope-square" aria-hidden="true"></i> chris.nicolini@gmail.com | [<i class="fa fa-globe" aria-hidden="true"></i> website](https://sicn1c.github.io/)</center>

***

### PROFESSIONAL EXPERIENCE  

Social Media Coordinator <span style="float:right;">2015 – present</span>   
University of California Davis, Strategic Communications -- Office of the Chancellor and Provost

Web Communications Specialist <span style="float:right;">2014 – 2015</span>   
University of California Davis, College of Agriculture and Environmental Sciences (CA&ES)

Editor and Producer <span style="float:right;">2008 – 2013</span>   
The American Institute of Physics, InsideScience.org

Affiliate Web Content Producer <span style="float:right;">2008</span>   
NBC Olympics, NBCOlympics.com

Research Technician  <span style="float:right;">2008-2009</span>  
University of North Carolina at Chapel Hill

Senior Online Producer <span style="float:right;">2006-2008</span>  
NBC-17 News, Raleigh NC

Head Cyberjouralist  <span style="float:right;">2005-2006</span> 
NBC-7 News, Boston MA

Web Producer  <span style="float:right;">2004-2005</span> 
ABC 11 News, Durham NC

Editor-in-Chief  <span style="float:right;">2003-2004</span> 
The Pine Needle Newspaper, Lumberton NC

Reporter   <span style="float:right;">2001-2003</span> 
The Robesonian Newspaper, Lumberton NC

***  

### EDUCATION 

B.A., Public Relations | B.A., Journalism 	<span style="float:right;">2004</span>  
University of North Carolina, Pembroke  

***

### TECHNICAL ACUMEN

Content Creation

* Experienced Copy Editor: The Associated Press Stylebook and Briefing on Media Law
* Advanced Adobe Photoshop user with over 20 years of experience
* Proficient with Adobe Creative Cloud Suite
* Videography
* Proficient HTML & CSS coder

Project & Program Management|Coordination

* Experienced using a wide range of Content Management Systems (Drupal, Wordpress, etc.)
* Experienced with various project management software (Airtable, Trello, Asana)

Analytics & Reporting

* Programming languages and software: Excel, Qualtrics, Markdown, R
* Version control (git)


***

### TEACHING EXPERIENCE   

Instructor |  University of California, Davis   
  First Year Aggie Connection: Photography for Social Media <span style="float:right;">quarter year</span>  

Instructor |  University of California, Davis   
  First Year Aggie Connection: Photography <span style="float:right;">quarter year</span>  

***

### PRESENTATIONS  

**Nicolini, C** & ... (year, month). Title. Conference name. City, State. 

***

### SELECTED CERTIFICATES & TRAINING

UC Davis Leadership Program <span style="float:right;">quarter year</span> 

***

### SELECTED AWARDS  
name  <span style="float:right;"> year</span>  

***

### SERVICE

name  <span style="float:right;"> year</span>  

***

### ORGANIZATIONS

* UC Davis Campus Communicators  <span style="float:right;"> year</span>
* Capitol Science Communicators  <span style="float:right;"> year</span>
* American Academy of Underwater Scientists <span style="float:right;"> 2008-2009</span>

***
